# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

#development:
#  <<: *default
#  database: db/development.sqlite3

#test:
#  <<: *default
#  database: db/test.sqlite3

#production:
#  <<: *default
#  database: db/production.sqlite3


# postgres db

development:
  adapter: postgresql
  encoding: unicode
  database: sample
  pool: 5
  username: social
  password: 12345678
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sample_test
  pool: 5
  username: social
  password: 12345678
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: sample
  pool: 5
  username: social
  password: 12345678
